export { default as Home } from './Home.vue'
export { default as LandingPage } from './LandingPage.vue'
export { default as Login } from './Login.vue'
export { default as Register } from './Register.vue'
export { default as NewQuery } from './NewQuery.vue'
export { default as Doctors } from './Doctors.vue'
export { default as Patients } from './Patients.vue'
