export { default as User } from './user'
export { default as Deficiency } from './deficiency'
export { default as Dependency } from './dependency'
export { default as Occupation } from './occupation'
export { default as Hospital } from './hospital'
export { default as Patient } from './patient'
export { default as Doctor } from './doctor'
export { default as Exam } from './exam'
export { default as Query } from './query'
export { default as MedicalClearance } from './medicalClearance'
export { default as Session } from './session'
export { default as Statistic } from './statistic'

export { default as DoctorTable } from './tables/doctorTable'
export { default as PatientTable } from './tables/patientTable'
